name: example
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  rspl_network_manager:
    path: ../
  dio: ^5.1.2
  dio_smart_retry: ^7.0.1
  json_serializable: ^6.5.4
  json_annotation: ^4.9.0
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  go_router: ^17.0.0
  formz: ^0.8.0
  equatable: ^2.0.5
  get_it: ^9.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dependency_overrides:
  win32: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/json/
